### ISSUE TITLE
Load and Layout vs Re-Layout produce different results in demo

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#10]
If you select the sample "n20_e32_i0" and hit "Load and Layout Sample", you typically get a pretty layout but if instead perform a Re-Layout, the results isn't good at all. Why the discrepancy?

**Comment by hamzaislam101** [comment]
graphml was running cose in the background when loading the graph. Plus the totaldisplacement was not taken into account for the undirected part during iterations.
