### ISSUE TITLE
add a button to assign random width and height to nodes

### ISSUE THREAD

**Issue by hamzaislam101** [iVis-at-Bilkent/cytoscape.js-hyse#12]
Add a button in the demo, which upon clicking will assign some random width and height to the nodes of the graph.

**Comment by ugurdogrusoz** [comment]
Can we increase the variation (upper limit) a bit? Upper limit could be 2 times the current dimension.

**Comment by hamzaislam101** [comment]
I increased it. But then we had a problem with rank gap as well because we were using half of the max height to each side of a rank. Now the rank gap max height + constant (20).
