### ISSUE TITLE
create a user input to choose if post processing should be done or not

### ISSUE THREAD

**Issue by hamzaislam101** [iVis-at-Bilkent/cytoscape.js-hyse#13]
Add a check box that allows the user to choose if they want to run the post-processing method on the given graph.

**Comment by ugurdogrusoz** [comment]
Is this box actually considered? I am seeing overlaps but I am not sure it's less often when this is checked.

**Comment by hamzaislam101** [comment]
The checkbox is working, but the post-processing method is not, because it is flawed at the moment. I'll try to fix it.

**Comment by hamzaislam101** [comment]
The repulsion method is added to the post layout iterations
