### ISSUE TITLE
Further demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#29]
- [x] 1. Rename settings section titles: "Save/Load" -> "File", "HySE" -> "HySE Options", "Graph Ops" -> "Graph Operations", "Cose/Dagre" -> "CoSE/Dagre Layout", "Experiment/Test" -> "Experiments"
- [x] 2. Shorter title background for accordions (2/3 of what it is now?)
- [x] 3. For all settings, review the label and tooltips. Also make sure capitalization is consistent (i.e., "Ideal edge length")
- [x] 4. Change the default for Animation tick delay from 100 to 10
- [x] 5. Can we automatically load a new sample when the selection in the dropdown box changes (as opposed to having to click "Load sample")?
- [x] 6. In File > Load, add ellipses "Load.." (as it opens up a dialog)
- [x] 7. "Run experiment" needs a more detailed tooltip explanation
- [x] 8. "Create test graph" tooltip could say "Create a test graph with above parameters"
- [x] 9. The color coding of the borders to mark swaps could be made optional (false by default)

**Comment by hamzaislam101** [comment]
Pushed the mentioned changes.
