### ISSUE TITLE
Demo improvements 2

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#3]
- [x] Why do we have so many different border colors for the nodes in the hierarchy? Let's use the same color for the border of the nodes in the hierarchy as their background color (all yellowish).
- [x] Let's use a lighter gray for the background of nodes outside the hierarchy so that when they are selected and their background becomes black, they are more distinguishable from the others.
- [x] Looks like "Run Layout" actually loads the selected sample and runs layout on it. So let's rename it as "Load and Layout Sample"
- [x] "Add Selected to Hierarchy" -> "Add Selected to Hierarch and Re-Layout"
- [x] "ReRun" -> "Re-Layout"
- [x] Leave some minimal space between the buttons and the canvas.
- [x] Adjust the wheel sensitivity so that it zooms in and out more slowly.

**Comment by hamzaislam101** [comment]
Pushed the changes for these.
