### ISSUE TITLE
API review

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#30]
- [x] 1. I do not understand what this option is. Change naming and/or explanation: animationDuration: 1000
- [x] 2. // Apply repulsion forces on the graph to avoid node overlaps
  performPostProcessing: true,
Should we instead say "// Apply stronger repulsion forces in the directed part to avoid node overlaps"?
- [x] 3. Change default for tickDelay to 10

**Comment by hamzaislam101** [comment]
It is the time that it takes to move the nodes in an animated way when the layout is run, taken from fcose, and eventually handled in cytoscape.js

**Comment by hamzaislam101** [comment]
2. No, that would give a completely different meaning to it. It might convey that we are applying different and increased repulsion forces in the directed part. We can mention running extra iterations for the directed part.
