### ISSUE TITLE
Add sample graphs with non-uniform node dimensions to the demo

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#6]
Make sure both the hierarchical nodes and non-hierarchical ones are of non-uniform node dimensions.

**Comment by hamzaislam101** [comment]
I am working on this. I have pushed the graph with compound nodes in non-hierarchical parts. If I add compounds to the hierarchy, the layout does not work properly. I'll add the nodes with different sizes now.

**Comment by hamzaislam101** [comment]
The layout tries to make no overlaps in the hierarchy, but they still happen to overlap sometimes. I think it might be because of the distance between the ranks/levels in the hierarchy.
