### ISSUE TITLE
Add CoSE layout for comparison to the demo

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#7]
Being able to check and compare CoSE layout with this one in an animated manner could be useful.

**Comment by hamzaislam101** [comment]
Added cose-bilkent for demo. The animation uses only the ticks per frame option.

**Comment by ugurdogrusoz** [comment]
Nice. Let's rearrange and style the buttons as follows. Change the labels of buttons and order of buttons as follows (keeping current labels as tooltips)
    o "Load and Layout Sample" -> "Load Sample"
    o "Load Graph from File" -> "Load"
    o "Add Selected to Hierarchy and Re-Layout" -> "Add to Hierarchy"
    o "Re-Layout" -> "HySE"
    o "Run Animated Layout" -> "HySE Animated"
    o "Tick Delay" 
    o "Ticks per frame" -> "Ticks Per Frame"
    o "Run Cose" -> "CoSE"
    o "Run Cose Animated" -> "CoSE Animated"

**Comment by ugurdogrusoz** [comment]
Nice but we're missing the tooltips (old labels should have stayed as tooltips).

**Comment by hamzaislam101** [comment]
Do we want to remove the delete selected button?

**Comment by ugurdogrusoz** [comment]
> Do we want to remove the delete selected button?

No actually, I must have missed it. Let's keep it before "HySE" button.
