### ISSUE TITLE
Demo improvement

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#8]
Nodes (n6 & n8 below) added later on to the hierarchy still has the border color of the non-hierarchy component they were in before, confusing the user. We should reset their borders to be the same as others on the hierarchy.
![Screenshot 2023-02-09 155430](https://user-images.githubusercontent.com/3874988/217818533-69a2c089-67b7-4940-809d-31aa6fd096c0.png)

**Comment by hamzaislam101** [comment]
Pushed the changes. The style selector was not working after it ran the first time. I had to manually set the color of the borders in the before layout function.
