### ISSUE TITLE
Overlapping nodes in the hierarchy

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-hyse#9]
As can be seen from the default graph in the demo, the nodes with varying dimensions in the hierarchy often overlap with each other in the y dimension. So, the separation of levels that should be calculated based on the tallest node in that level must be buggy.

**Comment by hamzaislam101** [comment]
rank gap now would be 1.5 times the height of the tallest node. Hierarchical nodes do overlap horizontally sometimes, which is inherited from HiSE. I'll debug this one again.

**Comment by ugurdogrusoz** [comment]
Sounds like this can only be a temporary solution. Using 1.5 times the tallest node is going to result in unnecessary space, which is critical as a layout quality. For instance if the tallest node is of 200 units high, then we dedicate an extra 100 units, where 20 units fixed space would suffice.

**Comment by hamzaislam101** [comment]
Added 20 units to the height of the tallest node to get the rank gap value.

**Comment by ugurdogrusoz** [comment]
It looks like the separation is much bigger? Also, why the frequent overlap of nodes horizontally (not vertically)?
![image](https://user-images.githubusercontent.com/3874988/218747564-13f8da55-fe3d-46eb-af8d-9db5ab1f29e1.png)

**Comment by hamzaislam101** [comment]
The rank gap should have been (half of the tallest + the constant) because the node is placed half on both sides. I corrected it.

**Comment by hamzaislam101** [comment]
The horizontal overlap is from HiSE. I tried correcting this before but couldn't do so. I'll go over this again.

**Comment by ugurdogrusoz** [comment]
The only issue left here is horizontal overlap now.

**Comment by ugurdogrusoz** [comment]
With the help of the "repulsion only" phase, this seems to have been resolved. Thanks!
